# AI-chatbot

Aim of this excercise is is to design a bot that can answer students' query.

In [1]:
import pandas as pd
import numpy
import random

In [2]:
import nltk
from nltk.stem import WordNetLemmatizer
lemm = WordNetLemmatizer()

In [5]:
import tflearn
import tensorflow as tf

In [6]:
data = pd.read_json('chatbot.json')
data

intents
0  {'tag': 'greeting', 'patterns': ['Hi', 'How ar...
1  {'tag': 'goodbye', 'patterns': ['cya', 'byeSee...
2  {'tag': 'age', 'patterns': ['how old', 'how ol...
3  {'tag': 'name', 'patterns': ['what is your nam...
4  {'tag': 'profession', 'patterns': ['Id like to...
5  {'tag': 'hours', 'patterns': ['when are you av...

In [7]:
import json
with open('chatbot.json') as file:
    data2 = json.load(file)

In [8]:
print(data2)

{'intents': [{'tag': 'greeting', 'patterns': ['Hi', 'How are you', 'Is anyone there?', 'Hello', 'Good day', 'Whats up'], 'responses': ['Hello!', 'Good to see you again!', 'Hi there, how can I help?'], 'context_set': ''}, {'tag': 'goodbye', 'patterns': ['cya', 'byeSee you later', 'Goodbye', 'Good bye', 'I am Leaving', 'Have a Good day'], 'responses': ['Sad to see you go :(', 'Talk to you later', 'Goodbye!'], 'context_set': ''}, {'tag': 'age', 'patterns': ['how old', 'how old is Hassan', 'what is your age', 'how old are you', 'age?'], 'responses': ['I am 32 years old!', '32 years young!'], 'context_set': ''}, {'tag': 'name', 'patterns': ['what is your name', 'what should I call you', 'whats your name?'], 'responses': ['You can call me Hassan.', "I'm Hassan!", "I'm Hassan Sherwani.You may call me Hassan."], 'context_set': ''}, {'tag': 'profession', 'patterns': ['Id like to get some information about you', 'what is your profession', 'what do you do for work?', 'Could I know what is your fi

In [9]:
print(data2["intents"])

[{'tag': 'greeting', 'patterns': ['Hi', 'How are you', 'Is anyone there?', 'Hello', 'Good day', 'Whats up'], 'responses': ['Hello!', 'Good to see you again!', 'Hi there, how can I help?'], 'context_set': ''}, {'tag': 'goodbye', 'patterns': ['cya', 'byeSee you later', 'Goodbye', 'Good bye', 'I am Leaving', 'Have a Good day'], 'responses': ['Sad to see you go :(', 'Talk to you later', 'Goodbye!'], 'context_set': ''}, {'tag': 'age', 'patterns': ['how old', 'how old is Hassan', 'what is your age', 'how old are you', 'age?'], 'responses': ['I am 32 years old!', '32 years young!'], 'context_set': ''}, {'tag': 'name', 'patterns': ['what is your name', 'what should I call you', 'whats your name?'], 'responses': ['You can call me Hassan.', "I'm Hassan!", "I'm Hassan Sherwani.You may call me Hassan."], 'context_set': ''}, {'tag': 'profession', 'patterns': ['Id like to get some information about you', 'what is your profession', 'what do you do for work?', 'Could I know what is your field?'], 'res

In [10]:
# for loading in all our words and labels and getting document ready with diff. pattern
words = []
labels = []
docs_x = []
docs_y = []

for intent in data['intents']:
    for pattern in intent['patterns']: # tokenize words inside pattern 
        wrds = nltk.word_tokenize(pattern)
        words.extend(wrds)
        docs_x.append(wrds)
        docs_y.append(intent["tag"])
        
    if intent['tag'] not in labels:
        labels.append(intent['tag'])

In [11]:
print(words)

['Hi', 'How', 'are', 'you', 'Is', 'anyone', 'there', '?', 'Hello', 'Good', 'day', 'Whats', 'up', 'cya', 'byeSee', 'you', 'later', 'Goodbye', 'Good', 'bye', 'I', 'am', 'Leaving', 'Have', 'a', 'Good', 'day', 'how', 'old', 'how', 'old', 'is', 'Hassan', 'what', 'is', 'your', 'age', 'how', 'old', 'are', 'you', 'age', '?', 'what', 'is', 'your', 'name', 'what', 'should', 'I', 'call', 'you', 'whats', 'your', 'name', '?', 'Id', 'like', 'to', 'get', 'some', 'information', 'about', 'you', 'what', 'is', 'your', 'profession', 'what', 'do', 'you', 'do', 'for', 'work', '?', 'Could', 'I', 'know', 'what', 'is', 'your', 'field', '?', 'when', 'are', 'you', 'available', 'for', 'discussion', '?', 'what', 'are', 'your', 'office', 'hours', 'hours', 'of', 'work']


In [12]:
print(labels)

['greeting', 'goodbye', 'age', 'name', 'profession', 'hours']


In [13]:
print(docs_x)

[['Hi'], ['How', 'are', 'you'], ['Is', 'anyone', 'there', '?'], ['Hello'], ['Good', 'day'], ['Whats', 'up'], ['cya'], ['byeSee', 'you', 'later'], ['Goodbye'], ['Good', 'bye'], ['I', 'am', 'Leaving'], ['Have', 'a', 'Good', 'day'], ['how', 'old'], ['how', 'old', 'is', 'Hassan'], ['what', 'is', 'your', 'age'], ['how', 'old', 'are', 'you'], ['age', '?'], ['what', 'is', 'your', 'name'], ['what', 'should', 'I', 'call', 'you'], ['whats', 'your', 'name', '?'], ['Id', 'like', 'to', 'get', 'some', 'information', 'about', 'you'], ['what', 'is', 'your', 'profession'], ['what', 'do', 'you', 'do', 'for', 'work', '?'], ['Could', 'I', 'know', 'what', 'is', 'your', 'field', '?'], ['when', 'are', 'you', 'available', 'for', 'discussion', '?'], ['what', 'are', 'your', 'office', 'hours'], ['hours', 'of', 'work']]


In [14]:
print(docs_y)

['greeting', 'greeting', 'greeting', 'greeting', 'greeting', 'greeting', 'goodbye', 'goodbye', 'goodbye', 'goodbye', 'goodbye', 'goodbye', 'age', 'age', 'age', 'age', 'age', 'name', 'name', 'name', 'profession', 'profession', 'profession', 'profession', 'hours', 'hours', 'hours']


# Preprocessing data

In [15]:
words = [lemm.lemmatize(w.lower()) for w in words if w != "?"]
words = sorted(list(set(words))) # removes any duplicates if ever occured

In [16]:
print(words)

['a', 'about', 'age', 'am', 'anyone', 'are', 'available', 'bye', 'byesee', 'call', 'could', 'cya', 'day', 'discussion', 'do', 'field', 'for', 'get', 'good', 'goodbye', 'hassan', 'have', 'hello', 'hi', 'hour', 'how', 'i', 'id', 'information', 'is', 'know', 'later', 'leaving', 'like', 'name', 'of', 'office', 'old', 'profession', 'should', 'some', 'there', 'to', 'up', 'what', 'whats', 'when', 'work', 'you', 'your']


In [17]:
labels = sorted(labels)

In [18]:
print(labels)

['age', 'goodbye', 'greeting', 'hours', 'name', 'profession']


**We have 6 labels. So, we will have pattern of 6 encoded terms**

### Bag of Words

- Converting out strings of words into numerical input.<br>

- represent each sentence with a list the length of the amount of words in our models vocabulary. Each position in the list will represent a word from our vocabulary. If the position in the list is a 1 then that will mean that the word exists in our sentence, if it is a 0 then the word is nor present

- bag of words because the order in which the words appear in the sentence is lost, we only know the presence of words in our models vocabulary.

In [19]:
training = []
output = []

out_empty = [0 for _ in range(len(labels))]

for x, doc in enumerate(docs_x):
    bag = []

    wrds = [lemm.lemmatize(w.lower()) for w in doc]

    for w in words:
        if w in wrds:
            bag.append(1)
        else:
            bag.append(0)

    output_row = out_empty[:]
    output_row[labels.index(docs_y[x])] = 1

    training.append(bag)
    output.append(output_row)

In [20]:
# Our neural network will take arrays so, we need to convert
training = numpy.array(training)
output = numpy.array(output)

In [21]:
print(training)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 1 0 0]]


In [22]:
len(training)

27

In [23]:
len(training[0])

50

In [24]:
#labels
print(output)

[[0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 1 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]]


In [25]:
len(labels)

6

In [26]:
len(output[0])

6

['age', 'goodbye', 'greeting', 'hours', 'name', 'shop'] are encoded in this step.

output lists which are the length of the amount of labels/tags we have in our dataset. Each position in the list will represent one distinct label/tag, a 1 in any of those positions will show which label/tag is represented.

# Developing a Model

In [27]:
tf.reset_default_graph()

net = tflearn.input_data(shape=[None, len(training[0])])
net = tflearn.fully_connected(net, 8)
net = tflearn.fully_connected(net, 8)
net = tflearn.fully_connected(net, len(output[0]), activation="softmax")
net = tflearn.regression(net)

model = tflearn.DNN(net)

In [28]:
history=model.fit(training, output, n_epoch=800, batch_size=8, show_metric=True)

Training Step: 3199  | total loss: 0.45014 | time: 0.005s
| Adam | epoch: 800 | loss: 0.45014 - acc: 0.9428 -- iter: 24/27
Training Step: 3200  | total loss: 0.41523 | time: 0.006s
| Adam | epoch: 800 | loss: 0.41523 - acc: 0.9485 -- iter: 27/27
--


In [29]:
model.save("bot.tflearn")

INFO:tensorflow:C:\Users\69785hsh\Downloads\Data Science\Learning Projects\chatbot\bot.tflearn is not in all_model_checkpoint_paths. Manually adding it.


# Predictions

In [30]:
def bag_of_words(s, words):
    bag = [0 for _ in range(len(words))]

    s_words = nltk.word_tokenize(s)
    s_words = [lemm.lemmatize(word.lower()) for word in s_words]

    for se in s_words:
        for i, w in enumerate(words):
            if w == se:
                bag[i] = 1
            
    return numpy.array(bag)


def chat():
    print("Start talking with the bot (type close to stop)!")
    while True:
        inp = input("User: ")
        if inp.lower() == "close":
            break

        results = model.predict([bag_of_words(inp, words)]) # shows results with probability of each neurons with that word. 
        results_index = numpy.argmax(results) # to give maximum of index out of all neurons.
        tag = labels[results_index]

        for tg in data["intents"]:
            if tg['tag'] == tag:
                responses = tg['responses']

        print(random.choice(responses))

chat()

Start talking with the bot (type close to stop)!
User: Is anyone there?
Good to see you again!
User: Whats up?
Hi there, how can I help?
User: what should I call you?
I'm Hassan!
User: close


### checking probability of  discussion

In [31]:
def bag_of_words(s, words):
    bag = [0 for _ in range(len(words))]

    s_words = nltk.word_tokenize(s)
    s_words = [lemm.lemmatize(word.lower()) for word in s_words]

    for se in s_words:
        for i, w in enumerate(words):
            if w == se:
                bag[i] = 1
            
    return numpy.array(bag)


def chat():
    print("Start talking with the bot (type close to stop)!")
    while True:
        inp = input("User: ")
        if inp.lower() == "close":
            break

        results = model.predict([bag_of_words(inp, words)]) # shows results with probability of each neurons with that word. 
        results_index = numpy.argmax(results) # to give maximum of index out of all neurons.
        tag = labels[results_index]
        print(results)

        for tg in data["intents"]:
            if tg['tag'] == tag:
                responses = tg['responses']

        print(random.choice(responses))

chat()

Start talking with the bot (type close to stop)!
User: hi
[[3.1950664e-02 6.2040379e-03 9.4528866e-01 6.6862121e-05 1.6456170e-02
  3.3628821e-05]]
Hi there, how can I help?
User: what is your name?
[[6.5878950e-02 9.5405958e-05 2.8744360e-02 2.8601135e-04 8.4643829e-01
  5.8556996e-02]]
You can call me Hassan.
User: close


### For a smarter bot

In [32]:
def bag_of_words(s, words):
    bag = [0 for _ in range(len(words))]

    s_words = nltk.word_tokenize(s)
    s_words = [lemm.lemmatize(word.lower()) for word in s_words]

    for se in s_words:
        for i, w in enumerate(words):
            if w == se:
                bag[i] = 1
            
    return numpy.array(bag)


def chat():
    print("Start talking with the bot (type close to stop)!")
    while True:
        inp = input("User: ")
        if inp.lower() == "close":
            break

        results = model.predict([bag_of_words(inp, words)])[0] # for words that are not understood
        results_index = numpy.argmax(results) # to give maximum of index out of all neurons.
        tag = labels[results_index]
        if results[results_index] > 0.65:

            for tg in data["intents"]:
                if tg['tag'] == tag:
                    responses = tg['responses']
        
            print(random.choice(responses))
        else:
            print("I didn't get your question. Please try again")

chat()

Start talking with the bot (type close to stop)!
User: whats your name?
I'm Hassan!
User: Could I know what is your field?
I am third year PhD student at RSM. My research focus is on Natural Language Processing
User: Do you know Mr. T from Rocky movie?
I didn't get your question. Please try again
User: what are your office hours?
I am available from 10-12 every Thursday.
User: cya
Goodbye!
User: close
