# Detecting Programming Language

Evaluation

# 1)- Importing key libraries

In [1]:

#support both Python 2 and Python 3 with minimal overhead.
from __future__ import absolute_import, division, print_function

# I am an engineer. I care only about error not warning. So, let's be maverick and ignore warnings.
import warnings
warnings.filterwarnings('ignore')

In [2]:
# For data processing and maths
import numpy as np
import pandas as pd
import time
import math
import os
#For Visuals
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from matplotlib import rcParams
rcParams['figure.figsize'] = 11, 8
%config InlineBackend.figure_format = 'svg'
%matplotlib inline

In [3]:
# ! pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz

In [4]:
# For text we shall use Spacy

import spacy 
from spacy import displacy
from spacy.matcher import Matcher
nlp = spacy.load("en_core_web_sm")

In [5]:
#! pip install version_information

In [6]:
%reload_ext version_information
%version_information pandas,spacy,numpy,seaborn, matplotlib

Software versions
Python 3.7.5 64bit [Clang 4.0.1 (tags/RELEASE_401/final)]
IPython 7.10.2
OS Darwin 19.2.0 x86_64 i386 64bit
pandas 0.25.3
spacy 2.2.3
numpy 1.17.4
seaborn 0.9.0
matplotlib 3.1.1
Sun Jan 05 17:01:32 2020 CET

# 2)- Loading Data

In [7]:
data= pd.read_csv("Questions.csv", nrows=1_000_00, encoding="ISO-8859-1")

In [8]:
data.head()

Id  OwnerUserId          CreationDate            ClosedDate  Score  \
0   80         26.0  2008-08-01T13:57:07Z                   NaN     26   
1   90         58.0  2008-08-01T14:41:24Z  2012-12-26T03:45:49Z    144   
2  120         83.0  2008-08-01T15:50:08Z                   NaN     21   
3  180    2089740.0  2008-08-01T18:42:19Z                   NaN     53   
4  260         91.0  2008-08-01T23:22:08Z                   NaN     49   

                                               Title  \
0  SQLStatement.execute() - multiple queries in o...   
1  Good branching and merging tutorials for Torto...   
2                                  ASP.NET Site Maps   
3                 Function for creating color wheels   
4  Adding scripting functionality to .NET applica...   

                                                Body  
0  <p>I've written a database generation script i...  
1  <p>Are there any really good tutorials explain...  
2  <p>Has anyone got experience creating <strong>...  
3  <p>This is something I've pseudo-solved many t...  
4  <p>I have a little game written in C#. It uses...

In [9]:
data.Body[8]

"<p>I would like the version property of my application to be incremented for each build but I'm not sure on how to enable this functionality in Visual Studio (2005/2008). I have tried to specify the AssemblyVersion as 1.0.* but it doesn't get me exactly what I want. </p>\r\n\r\n<p>I'm also using a settings file and in earlier attempts when the assembly version changed my settings got reset to the default since the application looked for the settings file in another directory. </p>\r\n\r\n<p>I would like to be able to display a version number in the form of 1.1.38 so when a user finds a problem I can log the version they are using as well as tell them to upgrade if they have an old release.</p>\r\n\r\n<p>A short explanation of how the versioning works would also be appreciated. When does the build and revision number get incremented?</p>"

In [10]:
data.Title[8]

'Automatically update version number'

In [11]:
#col.s of our concern

df=data[['Id','Title']]
df.head()

Id                                              Title
0   80  SQLStatement.execute() - multiple queries in o...
1   90  Good branching and merging tutorials for Torto...
2  120                                  ASP.NET Site Maps
3  180                 Function for creating color wheels
4  260  Adding scripting functionality to .NET applica...

In [12]:
df.shape

(100000, 2)

In [13]:
df.Title[4]

'Adding scripting functionality to .NET applications'

# 3)-Labeling data

In [14]:
df_labelling = (pd.read_csv("Questions.csv", nrows=500,
                  encoding="ISO-8859-1", usecols=['Title', 'Id']))

In [15]:
df_labelling.shape

(500, 2)

In [16]:
df_labelling.to_csv('label.csv')

In [17]:
label=pd.read_excel('label.xltx', index_col=0)

In [18]:
label.head()

Id                                              Title  Label
0   80  SQLStatement.execute() - multiple queries in o...      1
1   90  Good branching and merging tutorials for Torto...      0
2  120                                  ASP.NET Site Maps      0
3  180                 Function for creating color wheels      0
4  260  Adding scripting functionality to .NET applica...      1

now we have our labelled data for evaluation.

# 4)- Going back to Patterns

In [19]:
obj_c_pattern1 = [{'LOWER': 'objective'},
                  {'IS_PUNCT': True, 'OP': '?'},
                  {'LOWER': 'c'}]
obj_c_pattern2 = [{'LOWER': 'objectivec'}]
python_pattern = [{'LOWER': 'python'}]
go_pattern1    = [{'LOWER': 'go', 'POS': {'NOT_IN': ['VERB']}}]
go_pattern2    = [{'LOWER': 'golang'}]
ruby_pattern   = [{'LOWER': 'ruby'}]
js_pattern     = [{'LOWER': {'IN': ['js', 'javascript']}}]

matcher = Matcher(nlp.vocab, validate=True)
matcher.add("OBJ_C_LANG", None, obj_c_pattern1, obj_c_pattern2)
matcher.add("PYTHON_LANG", None, python_pattern)
matcher.add("GO_LANG", None, go_pattern1, go_pattern2)
matcher.add("JS_LANG", None, js_pattern)
matcher.add("RUBY_LANG", None, ruby_pattern)

In [20]:
#  for Python

titles = (_ for _ in df['Title'] if "ruby" in _.lower())

In [21]:
for i in range(200):
    doc = nlp(next(titles))
    if len(matcher(doc)) == 0:
        print(doc)

How do I get a zipped file's content using the rubyzip library?
What is the best way to add user ID to RubyOnRails log entries?
How to deploy an RubyGem-based Server
Getting Started with IronRuby on Rails
Persisting the state column on transition using rubyist-aasm (acts as state machine)
Connecting to MS SQL Server with JRuby
Is there an equivalent of isitruby19 for rubinius?
How to consume remoting in IronRuby
jruby on tomcat - RackInitializationException
Documentation on RubyVM::InstructionSequence?


In 6th case, JRuby/MS SQL, we are not sure if we have found results actually for python. So, we better highlight given entity.

### creating html generator

taken directly from tutorial 

In [22]:
from IPython.display import HTML as html_print

def style(s, bold=False):
    blob = f"<text>{s}</text>"
    if bold:
        blob = f"<b style='background-color: #fff59d'>{blob}</b>"
    return blob

def html_generator(g, n=10):
    blob = ""
    for i in range(n):
        doc = next(g)

        state = [[t, False] for t in doc]
        for idx, start, end in matcher(doc):
            for i in range(start, end):
                state[i][1] = True
        blob += style(' '.join([style(str(t[0]), bold=t[1]) for t in state]) + '<br>') 
    return blob

In [23]:
titles = (_ for _ in df['Title'])
g = (d for d in nlp.pipe(titles) if matcher(d))
html_print(html_generator(g, n=10))

# 5)-Results of Evaluation 1

In [24]:
obj_c_pattern1 = [{'LOWER': 'objective'},
                  {'IS_PUNCT': True, 'OP': '?'},
                  {'LOWER': 'c'}]
obj_c_pattern2 = [{'LOWER': 'objectivec'}]

csharp_pattern1 = [{'LOWER': 'c'}, {'LOWER': '#'}]
csharp_pattern2 = [{'LOWER': 'c'}, {'LOWER': 'sharp'}]
csharp_pattern3 = [{'LOWER': 'c#'}]

fsharp_pattern1 = [{'LOWER': 'f'}, {'LOWER': '#'}]
fsharp_pattern2 = [{'LOWER': 'f'}, {'LOWER': 'sharp'}]
fsharp_pattern3 = [{'LOWER': 'f#'}]
 
dot_net_pattern = [{'LOWER': '.net'}]

php_pattern = [{'LOWER': 'php'}]

asp_net_pattern = [{'LOWER': {'IN': ['asp.net', 'asp']}}]

python_pattern = [{'LOWER': 'python'}]

lisp_pattern1  = [{'LOWER': 'lisp'}]
lisp_pattern2  = [{'LOWER': 'common'}, {'LOWER': 'lisp'}]

go_pattern1    = [{'LOWER': 'go', 'POS': {'NOT_IN': ['VERB']}}]
go_pattern2    = [{'LOWER': 'golang'}]

ruby_pattern   = [{'LOWER': 'ruby'}]

sql_pattern    = [{'LOWER': 'sql'}]

matlab_pattern = [{'LOWER': 'matlab'}]

perl_pattern   = [{'LOWER': 'perl'}]

html_pattern   = [{'LOWER': 'html'}]

css_pattern   = [{'LOWER': 'css'}]

js_pattern     = [{'LOWER': {'IN': ['js', 'javascript']}}]

java_pattern   = [{'LOWER': 'java'}]

c_pattern      = [{'LOWER': 'c'}]

cpp_pattern    = [{'LOWER': 'c++'}]

matcher = Matcher(nlp.vocab, validate=True)
matcher.add("OBJ_C_LANG", None, obj_c_pattern1, obj_c_pattern2)
matcher.add("PYTHON_LANG", None, python_pattern)
matcher.add("GO_LANG", None, go_pattern1, go_pattern2)
matcher.add("CSHARP_LANG", None, csharp_pattern1, csharp_pattern2, csharp_pattern3)
matcher.add("FSHARP_LANG", None, fsharp_pattern1, fsharp_pattern2, fsharp_pattern3)
matcher.add("JS_LANG", None, js_pattern)
matcher.add("JAVA_LANG", None, java_pattern)
matcher.add("RUBY_LANG", None, ruby_pattern)
matcher.add("SQL_LANG", None, sql_pattern)
matcher.add("C_LANG", None, c_pattern)
matcher.add("CPP_LANG", None, cpp_pattern)
matcher.add("PHP_LANG", None, php_pattern)
matcher.add("MATLAB_LANG", None, matlab_pattern)
matcher.add("PERL_LANG", None, perl_pattern)
matcher.add("LISP_LANG", None, lisp_pattern1, lisp_pattern2)
matcher.add("HTML_LANG", None, html_pattern)
matcher.add("CSS_LANG", None, css_pattern)

### Actual Labelling

In [25]:
titles = (_ for _ in df['Title'][:2000])
sum(1 for d in nlp.pipe(titles) if matcher(d))

510

### Language Version

In [26]:
def create_versioned(name):
    return [
        [{'LOWER': name}], 
        [{'LOWER': {'REGEX': f'({name}\d+\.?\d*.?\d*)'}}], 
        [{'LOWER': name}, {'TEXT': {'REGEX': '(\d+\.?\d*.?\d*)'}}],
    ]

create_versioned('python')

[[{'LOWER': 'python'}],
 [{'LOWER': {'REGEX': '(python\\d+\\.?\\d*.?\\d*)'}}],
 [{'LOWER': 'python'}, {'TEXT': {'REGEX': '(\\d+\\.?\\d*.?\\d*)'}}]]

In [27]:
matcher = Matcher(nlp.vocab, validate=True)
matcher.add("PYTHON_LANG", None, *create_versioned('python'))
g = nlp.pipe(["i use python, python3.7, python 3.6.6", 
              "also python3, python 2 and python3.2.1", 
              "not bypython, pythonn and py36"])
html_print(html_generator(g, n=3))

### Putting this in a new matcher

In [28]:
obj_c_pattern1 = [{'LOWER': 'objective'},
                  {'IS_PUNCT': True, 'OP': '?'},
                  {'LOWER': 'c'}]
obj_c_pattern2 = [{'LOWER': 'objectivec'}]

csharp_pattern1 = [{'LOWER': 'c'}, {'LOWER': '#'}]
csharp_pattern2 = [{'LOWER': 'c'}, {'LOWER': 'sharp'}]
csharp_pattern3 = [{'LOWER': 'c#'}]

fsharp_pattern1 = [{'LOWER': 'f'}, {'LOWER': '#'}]
fsharp_pattern2 = [{'LOWER': 'f'}, {'LOWER': 'sharp'}]
fsharp_pattern3 = [{'LOWER': 'f#'}]

lisp_pattern1  = [{'LOWER': 'lisp'}]
lisp_pattern2  = [{'LOWER': 'common'}, {'LOWER': 'lisp'}]

go_pattern1    = [{'LOWER': 'go', 'POS': {'NOT_IN': ['VERB']}}]
go_pattern2    = [{'LOWER': 'golang'}]

html_pattern   = [{'LOWER': 'html'}]
css_pattern    = [{'LOWER': 'css'}]
sql_pattern    = [{'LOWER': 'sql'}]
js_pattern     = [{'LOWER': {'IN': ['js', 'javascript']}}]

cpp_pattern    = [{'LOWER': 'c++'}]


versioned_languages = ['ruby', 'php', 'python', 'perl', 'java', 'haskell', 
                       'scala', 'c', 'cpp', 'matlab', 'bash', 'delphi']
flatten = lambda l: [item for sublist in l for item in sublist]
versioned_patterns = flatten([create_versioned(lang) for lang in versioned_languages])

matcher = Matcher(nlp.vocab, validate=True)
matcher.add("PROG_LANG", None, 
            obj_c_pattern1, obj_c_pattern2,
            go_pattern1, go_pattern2,
            lisp_pattern1, lisp_pattern2,
            csharp_pattern1, csharp_pattern2, csharp_pattern3,
            fsharp_pattern1, fsharp_pattern2, fsharp_pattern3,
            html_pattern, css_pattern, sql_pattern, js_pattern,
            cpp_pattern, *versioned_patterns)

### On to evaluating

In [29]:
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report

label_df = (pd.read_excel('label.xltx')[['Title', 'Label']]
 .iloc[:90]
 .assign(Pred=lambda d: [len(matcher(d)) > 0 for d in nlp.pipe(d['Title'])])
 .assign(Label=lambda d: d['Label'].astype(np.int8))
 .assign(Pred=lambda d: d['Pred'].astype(np.int8)))

### Confusion Matrix

In [30]:
confusion_matrix(label_df['Label'], label_df['Pred'])

array([[54,  5],
       [13, 18]])

In [31]:
print(classification_report(label_df['Label'], label_df['Pred']))

              precision    recall  f1-score   support

           0       0.81      0.92      0.86        59
           1       0.78      0.58      0.67        31

    accuracy                           0.80        90
   macro avg       0.79      0.75      0.76        90
weighted avg       0.80      0.80      0.79        90



One reason of bad results for class 1 is that I have added SQL and ASP.NET as 1 and spacy might not read it as programming language.

# 6)-Machine learning approach

In [32]:
label=pd.read_excel('label.xltx', index_col=0)

In [33]:
label.head()

Id                                              Title  Label
0   80  SQLStatement.execute() - multiple queries in o...      1
1   90  Good branching and merging tutorials for Torto...      0
2  120                                  ASP.NET Site Maps      0
3  180                 Function for creating color wheels      0
4  260  Adding scripting functionality to .NET applica...      1

In [34]:
X=label.Title
y=label.Label

In [35]:
print(X.shape)
print(y.shape)

(500,)
(500,)


In [36]:
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split 
from sklearn.metrics import f1_score, accuracy_score, roc_curve,roc_auc_score,confusion_matrix, classification_report

In [37]:
# splitting data into training and test set
x_train, x_test, y_train, y_test = train_test_split(X, y,random_state=42,test_size=0.1)

In [38]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(450,)
(50,)
(450,)
(50,)


### 6.1)- Vectorization

In [39]:
from sklearn.feature_extraction.text import CountVectorizer

In [40]:
bow_vectorizer = CountVectorizer(max_df=0.90, min_df=2, max_features=300, stop_words='english')
# bag-of-words feature matrix
bow_train = bow_vectorizer.fit_transform(x_train)

In [41]:
bow_train.shape

(450, 300)

In [42]:
#We shall also apply vectorization by only using .transform

bow_test = bow_vectorizer.transform(x_test)
bow_test

<50x300 sparse matrix of type '<class 'numpy.int64'>'
	with 126 stored elements in Compressed Sparse Row format>

In [43]:
bow_test

<50x300 sparse matrix of type '<class 'numpy.int64'>'
	with 126 stored elements in Compressed Sparse Row format>

In [44]:
print(type(bow_train))
print(type(bow_test))

<class 'scipy.sparse.csr.csr_matrix'>
<class 'scipy.sparse.csr.csr_matrix'>


**Converting sparse to dense matrix**

In [45]:
bow_train

<450x300 sparse matrix of type '<class 'numpy.int64'>'
	with 1252 stored elements in Compressed Sparse Row format>

In [46]:
bow_train=bow_train.toarray()

In [47]:
type(bow_train)

numpy.ndarray

In [48]:
bow_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [49]:
bow_test=bow_test.toarray()

In [50]:
bow_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

### 6.2)- Applying Logistic Model 

In [51]:
lreg = LogisticRegression(solver='liblinear')

# training the model
lreg.fit(bow_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [52]:
bow_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [53]:
bow_test.shape

(50, 300)

### 6.3)-Predicting results

In [54]:
# predicting on the validation set
prediction = lreg.predict(bow_test)
prediction

array([0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0])

### 6.4)- Classification Report

In [55]:
print(classification_report(y_test, prediction))

              precision    recall  f1-score   support

           0       0.85      0.90      0.88        39
           1       0.56      0.45      0.50        11

    accuracy                           0.80        50
   macro avg       0.70      0.68      0.69        50
weighted avg       0.79      0.80      0.79        50



We can see how match method of spacy and machine learning model exhibit different results. 

- There should be more consistent modeling
- More cleaning of data might provide good results
- Some better and more precise model might provide better results